name = "Adjacently"
uuid = "411c8731-a39f-4a7d-8b26-fcc9fee4eb7b"
authors = ["Jimmy Dubuisson <jimmy.dubuisson@gmail.com>"]
version = "0.1.1"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DataStructures = "0.17.12"
Distances = "0.8.2"
GraphPlot = "0.4.2"
HDF5 = "0.13.1"
JLD = "0.9.2, 0.10"
LightGraphs = "1.3.1"
julia = "1.5"
